// Generated by iod_generate_symbols.
#include <iod/symbol.hh>



// #ifndef IOD_SYMBOL_Body
// #define IOD_SYMBOL_Body
//    iod_define_symbol(Body)
// #endif
//


#ifndef IOD_SYMBOL_cfg
#define IOD_SYMBOL_cfg
    iod_define_symbol(cfg)
#endif


#ifndef IOD_SYMBOL_port
#define IOD_SYMBOL_port
    iod_define_symbol(port);
#endif
#ifndef IOD_SYMBOL_nodaemon
#define IOD_SYMBOL_nodaemon
    iod_define_symbol(nodaemon);
#endif
//#ifndef IOD_SYMBOL_help
//#define IOD_SYMBOL_help
//    iod_define_symbol(help);
//#endif

#ifndef IOD_SYMBOL_text
#define IOD_SYMBOLtext
    iod_define_symbol(text);
#endif
#ifndef IOD_SYMBOL_freeling
#define IOD_SYMBOL_freeling
    iod_define_symbol(freeling);
#endif



