// Generated by iod_generate_symbols.
#include <iod/symbol.hh>



// #ifndef IOD_SYMBOL_Body
// #define IOD_SYMBOL_Body
//    iod_define_symbol(Body)
// #endif
//


#ifndef IOD_SYMBOL_cfg
#define IOD_SYMBOL_cfg
    iod_define_symbol(cfg)
#endif


#ifndef IOD_SYMBOL_port
#define IOD_SYMBOL_port
    iod_define_symbol(port);
#endif
#ifndef IOD_SYMBOL_nodaemon
#define IOD_SYMBOL_nodaemon
    iod_define_symbol(nodaemon);
#endif
//#ifndef IOD_SYMBOL_help
//#define IOD_SYMBOL_help
//    iod_define_symbol(help);
//#endif

#ifndef IOD_SYMBOL_word
#define IOD_SYMBOL_word
    iod_define_symbol(word);
#endif

#ifndef IOD_SYMBOL_lemma
#define IOD_SYMBOL_lemma
    iod_define_symbol(lemma);
#endif
#ifndef IOD_SYMBOL_tag
#define IOD_SYMBOL_tag
    iod_define_symbol(tag);
#endif


#ifndef IOD_SYMBOL_text
#define IOD_SYMBOL_text
    iod_define_symbol(text);
#endif

#ifndef IOD_SYMBOL_freeling
#define IOD_SYMBOL_freeling
    iod_define_symbol(freeling);
#endif

#ifndef IOD_SYMBOL_name
#define IOD_SYMBOL_name
    iod_define_symbol(name);
#endif

#ifndef IOD_SYMBOL_version_major
#define IOD_SYMBOL_version_major
    iod_define_symbol(version_major);
#endif

#ifndef IOD_SYMBOL_version_minor
#define IOD_SYMBOL_version_minor
    iod_define_symbol(version_minor);
#endif

#ifndef IOD_SYMBOL_uptime
#define IOD_SYMBOL_uptime
    iod_define_symbol(uptime);
#endif

